# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kessel/relations/v1beta1/common.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'kessel/relations/v1beta1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%kessel/relations/v1beta1/common.proto\x12\x18kessel.relations.v1beta1\x1a\x1b\x62uf/validate/validate.proto\"\xd0\x01\n\x0cRelationship\x12M\n\x08resource\x18\x01 \x01(\x0b\x32).kessel.relations.v1beta1.ObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\x08resource\x12#\n\x08relation\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x08relation\x12L\n\x07subject\x18\x03 \x01(\x0b\x32*.kessel.relations.v1beta1.SubjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\x07subject\"\x8d\x01\n\x10SubjectReference\x12\x1f\n\x08relation\x18\x01 \x01(\tH\x00R\x08relation\x88\x01\x01\x12K\n\x07subject\x18\x02 \x01(\x0b\x32).kessel.relations.v1beta1.ObjectReferenceB\x06\xbaH\x03\xc8\x01\x01R\x07subjectB\x0b\n\t_relation\"}\n\x11RequestPagination\x12\x1d\n\x05limit\x18\x01 \x01(\rB\x07\xbaH\x04*\x02 \x00R\x05limit\x12\x32\n\x12\x63ontinuation_token\x18\x02 \x01(\tH\x00R\x11\x63ontinuationToken\x88\x01\x01\x42\x15\n\x13_continuation_token\"C\n\x12ResponsePagination\x12-\n\x12\x63ontinuation_token\x18\x01 \x01(\tR\x11\x63ontinuationToken\"l\n\x0fObjectReference\x12@\n\x04type\x18\x01 \x01(\x0b\x32$.kessel.relations.v1beta1.ObjectTypeB\x06\xbaH\x03\xc8\x01\x01R\x04type\x12\x17\n\x02id\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x02id\"P\n\nObjectType\x12%\n\tnamespace\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\tnamespace\x12\x1b\n\x04name\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x04name\"\xb2\x01\n\x0b\x43onsistency\x12\x34\n\x10minimize_latency\x18\x01 \x01(\x08\x42\x07\xbaH\x04j\x02\x08\x01H\x00R\x0fminimizeLatency\x12W\n\x11\x61t_least_as_fresh\x18\x02 \x01(\x0b\x32*.kessel.relations.v1beta1.ConsistencyTokenH\x00R\x0e\x61tLeastAsFreshB\x14\n\x0brequirement\x12\x05\xbaH\x02\x08\x01\"1\n\x10\x43onsistencyToken\x12\x1d\n\x05token\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01R\x05tokenBr\n(org.project_kessel.api.relations.v1beta1P\x01ZDgithub.com/project-kessel/relations-api/api/kessel/relations/v1beta1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.relations.v1beta1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(org.project_kessel.api.relations.v1beta1P\001ZDgithub.com/project-kessel/relations-api/api/kessel/relations/v1beta1'
  _globals['_RELATIONSHIP'].fields_by_name['resource']._loaded_options = None
  _globals['_RELATIONSHIP'].fields_by_name['resource']._serialized_options = b'\272H\003\310\001\001'
  _globals['_RELATIONSHIP'].fields_by_name['relation']._loaded_options = None
  _globals['_RELATIONSHIP'].fields_by_name['relation']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_RELATIONSHIP'].fields_by_name['subject']._loaded_options = None
  _globals['_RELATIONSHIP'].fields_by_name['subject']._serialized_options = b'\272H\003\310\001\001'
  _globals['_SUBJECTREFERENCE'].fields_by_name['subject']._loaded_options = None
  _globals['_SUBJECTREFERENCE'].fields_by_name['subject']._serialized_options = b'\272H\003\310\001\001'
  _globals['_REQUESTPAGINATION'].fields_by_name['limit']._loaded_options = None
  _globals['_REQUESTPAGINATION'].fields_by_name['limit']._serialized_options = b'\272H\004*\002 \000'
  _globals['_OBJECTREFERENCE'].fields_by_name['type']._loaded_options = None
  _globals['_OBJECTREFERENCE'].fields_by_name['type']._serialized_options = b'\272H\003\310\001\001'
  _globals['_OBJECTREFERENCE'].fields_by_name['id']._loaded_options = None
  _globals['_OBJECTREFERENCE'].fields_by_name['id']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_OBJECTTYPE'].fields_by_name['namespace']._loaded_options = None
  _globals['_OBJECTTYPE'].fields_by_name['namespace']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_OBJECTTYPE'].fields_by_name['name']._loaded_options = None
  _globals['_OBJECTTYPE'].fields_by_name['name']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_CONSISTENCY'].oneofs_by_name['requirement']._loaded_options = None
  _globals['_CONSISTENCY'].oneofs_by_name['requirement']._serialized_options = b'\272H\002\010\001'
  _globals['_CONSISTENCY'].fields_by_name['minimize_latency']._loaded_options = None
  _globals['_CONSISTENCY'].fields_by_name['minimize_latency']._serialized_options = b'\272H\004j\002\010\001'
  _globals['_CONSISTENCYTOKEN'].fields_by_name['token']._loaded_options = None
  _globals['_CONSISTENCYTOKEN'].fields_by_name['token']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_RELATIONSHIP']._serialized_start=97
  _globals['_RELATIONSHIP']._serialized_end=305
  _globals['_SUBJECTREFERENCE']._serialized_start=308
  _globals['_SUBJECTREFERENCE']._serialized_end=449
  _globals['_REQUESTPAGINATION']._serialized_start=451
  _globals['_REQUESTPAGINATION']._serialized_end=576
  _globals['_RESPONSEPAGINATION']._serialized_start=578
  _globals['_RESPONSEPAGINATION']._serialized_end=645
  _globals['_OBJECTREFERENCE']._serialized_start=647
  _globals['_OBJECTREFERENCE']._serialized_end=755
  _globals['_OBJECTTYPE']._serialized_start=757
  _globals['_OBJECTTYPE']._serialized_end=837
  _globals['_CONSISTENCY']._serialized_start=840
  _globals['_CONSISTENCY']._serialized_end=1018
  _globals['_CONSISTENCYTOKEN']._serialized_start=1020
  _globals['_CONSISTENCYTOKEN']._serialized_end=1069
# @@protoc_insertion_point(module_scope)
