# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kessel.relations.v1beta1 import relation_tuples_pb2 as kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2


class KesselTupleServiceStub(object):
    """KesselTupleServices manages the persisted _Tuples_ stored in the system..

    A Tuple is an explicitly stated, persistent relation 
    between a Resource and a Subject or Subject Set. 
    It has the same _shape_ as a Relationship but is not the same thing as a Relationship.

    A single Tuple may result in zero-to-many Relationships.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTuples = channel.unary_unary(
                '/kessel.relations.v1beta1.KesselTupleService/CreateTuples',
                request_serializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.CreateTuplesRequest.SerializeToString,
                response_deserializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.CreateTuplesResponse.FromString,
                _registered_method=True)
        self.ReadTuples = channel.unary_stream(
                '/kessel.relations.v1beta1.KesselTupleService/ReadTuples',
                request_serializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ReadTuplesRequest.SerializeToString,
                response_deserializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ReadTuplesResponse.FromString,
                _registered_method=True)
        self.DeleteTuples = channel.unary_unary(
                '/kessel.relations.v1beta1.KesselTupleService/DeleteTuples',
                request_serializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.DeleteTuplesRequest.SerializeToString,
                response_deserializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.DeleteTuplesResponse.FromString,
                _registered_method=True)
        self.ImportBulkTuples = channel.stream_unary(
                '/kessel.relations.v1beta1.KesselTupleService/ImportBulkTuples',
                request_serializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ImportBulkTuplesRequest.SerializeToString,
                response_deserializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ImportBulkTuplesResponse.FromString,
                _registered_method=True)


class KesselTupleServiceServicer(object):
    """KesselTupleServices manages the persisted _Tuples_ stored in the system..

    A Tuple is an explicitly stated, persistent relation 
    between a Resource and a Subject or Subject Set. 
    It has the same _shape_ as a Relationship but is not the same thing as a Relationship.

    A single Tuple may result in zero-to-many Relationships.
    """

    def CreateTuples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTuples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTuples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportBulkTuples(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KesselTupleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTuples': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTuples,
                    request_deserializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.CreateTuplesRequest.FromString,
                    response_serializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.CreateTuplesResponse.SerializeToString,
            ),
            'ReadTuples': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadTuples,
                    request_deserializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ReadTuplesRequest.FromString,
                    response_serializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ReadTuplesResponse.SerializeToString,
            ),
            'DeleteTuples': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTuples,
                    request_deserializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.DeleteTuplesRequest.FromString,
                    response_serializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.DeleteTuplesResponse.SerializeToString,
            ),
            'ImportBulkTuples': grpc.stream_unary_rpc_method_handler(
                    servicer.ImportBulkTuples,
                    request_deserializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ImportBulkTuplesRequest.FromString,
                    response_serializer=kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ImportBulkTuplesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kessel.relations.v1beta1.KesselTupleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kessel.relations.v1beta1.KesselTupleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KesselTupleService(object):
    """KesselTupleServices manages the persisted _Tuples_ stored in the system..

    A Tuple is an explicitly stated, persistent relation 
    between a Resource and a Subject or Subject Set. 
    It has the same _shape_ as a Relationship but is not the same thing as a Relationship.

    A single Tuple may result in zero-to-many Relationships.
    """

    @staticmethod
    def CreateTuples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kessel.relations.v1beta1.KesselTupleService/CreateTuples',
            kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.CreateTuplesRequest.SerializeToString,
            kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.CreateTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadTuples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kessel.relations.v1beta1.KesselTupleService/ReadTuples',
            kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ReadTuplesRequest.SerializeToString,
            kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ReadTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTuples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kessel.relations.v1beta1.KesselTupleService/DeleteTuples',
            kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.DeleteTuplesRequest.SerializeToString,
            kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.DeleteTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportBulkTuples(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kessel.relations.v1beta1.KesselTupleService/ImportBulkTuples',
            kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ImportBulkTuplesRequest.SerializeToString,
            kessel_dot_relations_dot_v1beta1_dot_relation__tuples__pb2.ImportBulkTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
