# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from relations.v0 import check_pb2 as relations_dot_v0_dot_check__pb2


class KesselCheckServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/kessel.relations.v0.KesselCheckService/Check',
                request_serializer=relations_dot_v0_dot_check__pb2.CheckRequest.SerializeToString,
                response_deserializer=relations_dot_v0_dot_check__pb2.CheckResponse.FromString,
                )


class KesselCheckServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Checks for the existence of a single Relationship 
        (a Relation between a Resource and a Subject or Subject Set).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KesselCheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=relations_dot_v0_dot_check__pb2.CheckRequest.FromString,
                    response_serializer=relations_dot_v0_dot_check__pb2.CheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kessel.relations.v0.KesselCheckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KesselCheckService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kessel.relations.v0.KesselCheckService/Check',
            relations_dot_v0_dot_check__pb2.CheckRequest.SerializeToString,
            relations_dot_v0_dot_check__pb2.CheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
