# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: relations/v0/common.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19relations/v0/common.proto\x12\x13kessel.relations.v0\"\x90\x01\n\x0cRelationship\x12\x36\n\x08resource\x18\x01 \x01(\x0b\x32$.kessel.relations.v0.ObjectReference\x12\x10\n\x08relation\x18\x02 \x01(\t\x12\x36\n\x07subject\x18\x03 \x01(\x0b\x32%.kessel.relations.v0.SubjectReference\"m\n\x10SubjectReference\x12\x15\n\x08relation\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x35\n\x07subject\x18\x02 \x01(\x0b\x32$.kessel.relations.v0.ObjectReferenceB\x0b\n\t_relation\"Z\n\x11RequestPagination\x12\r\n\x05limit\x18\x01 \x01(\r\x12\x1f\n\x12\x63ontinuation_token\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x15\n\x13_continuation_token\"0\n\x12ResponsePagination\x12\x1a\n\x12\x63ontinuation_token\x18\x01 \x01(\t\"L\n\x0fObjectReference\x12-\n\x04type\x18\x01 \x01(\x0b\x32\x1f.kessel.relations.v0.ObjectType\x12\n\n\x02id\x18\x02 \x01(\t\"-\n\nObjectType\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tBG\n#org.project_kessel.api.relations.v0P\x01Z\x1e\x63iam-rebac/api/relations/v0;v0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relations.v0.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#org.project_kessel.api.relations.v0P\001Z\036ciam-rebac/api/relations/v0;v0'
  _globals['_RELATIONSHIP']._serialized_start=51
  _globals['_RELATIONSHIP']._serialized_end=195
  _globals['_SUBJECTREFERENCE']._serialized_start=197
  _globals['_SUBJECTREFERENCE']._serialized_end=306
  _globals['_REQUESTPAGINATION']._serialized_start=308
  _globals['_REQUESTPAGINATION']._serialized_end=398
  _globals['_RESPONSEPAGINATION']._serialized_start=400
  _globals['_RESPONSEPAGINATION']._serialized_end=448
  _globals['_OBJECTREFERENCE']._serialized_start=450
  _globals['_OBJECTREFERENCE']._serialized_end=526
  _globals['_OBJECTTYPE']._serialized_start=528
  _globals['_OBJECTTYPE']._serialized_end=573
# @@protoc_insertion_point(module_scope)
