# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from relations.v0 import relation_tuples_pb2 as relations_dot_v0_dot_relation__tuples__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in relations/v0/relation_tuples_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class KesselTupleServiceStub(object):
    """KesselTupleServices manages the persisted _Tuples_ stored in the system..

    A Tuple is an explicitly stated, persistent relation 
    between a Resource and a Subject or Subject Set. 
    It has the same _shape_ as a Relationship but is not the same thing as a Relationship.

    A single Tuple may result in zero-to-many Relationships.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTuples = channel.unary_unary(
                '/kessel.relations.v0.KesselTupleService/CreateTuples',
                request_serializer=relations_dot_v0_dot_relation__tuples__pb2.CreateTuplesRequest.SerializeToString,
                response_deserializer=relations_dot_v0_dot_relation__tuples__pb2.CreateTuplesResponse.FromString,
                _registered_method=True)
        self.ReadTuples = channel.unary_stream(
                '/kessel.relations.v0.KesselTupleService/ReadTuples',
                request_serializer=relations_dot_v0_dot_relation__tuples__pb2.ReadTuplesRequest.SerializeToString,
                response_deserializer=relations_dot_v0_dot_relation__tuples__pb2.ReadTuplesResponse.FromString,
                _registered_method=True)
        self.DeleteTuples = channel.unary_unary(
                '/kessel.relations.v0.KesselTupleService/DeleteTuples',
                request_serializer=relations_dot_v0_dot_relation__tuples__pb2.DeleteTuplesRequest.SerializeToString,
                response_deserializer=relations_dot_v0_dot_relation__tuples__pb2.DeleteTuplesResponse.FromString,
                _registered_method=True)


class KesselTupleServiceServicer(object):
    """KesselTupleServices manages the persisted _Tuples_ stored in the system..

    A Tuple is an explicitly stated, persistent relation 
    between a Resource and a Subject or Subject Set. 
    It has the same _shape_ as a Relationship but is not the same thing as a Relationship.

    A single Tuple may result in zero-to-many Relationships.
    """

    def CreateTuples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTuples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTuples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KesselTupleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTuples': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTuples,
                    request_deserializer=relations_dot_v0_dot_relation__tuples__pb2.CreateTuplesRequest.FromString,
                    response_serializer=relations_dot_v0_dot_relation__tuples__pb2.CreateTuplesResponse.SerializeToString,
            ),
            'ReadTuples': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadTuples,
                    request_deserializer=relations_dot_v0_dot_relation__tuples__pb2.ReadTuplesRequest.FromString,
                    response_serializer=relations_dot_v0_dot_relation__tuples__pb2.ReadTuplesResponse.SerializeToString,
            ),
            'DeleteTuples': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTuples,
                    request_deserializer=relations_dot_v0_dot_relation__tuples__pb2.DeleteTuplesRequest.FromString,
                    response_serializer=relations_dot_v0_dot_relation__tuples__pb2.DeleteTuplesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kessel.relations.v0.KesselTupleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kessel.relations.v0.KesselTupleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KesselTupleService(object):
    """KesselTupleServices manages the persisted _Tuples_ stored in the system..

    A Tuple is an explicitly stated, persistent relation 
    between a Resource and a Subject or Subject Set. 
    It has the same _shape_ as a Relationship but is not the same thing as a Relationship.

    A single Tuple may result in zero-to-many Relationships.
    """

    @staticmethod
    def CreateTuples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kessel.relations.v0.KesselTupleService/CreateTuples',
            relations_dot_v0_dot_relation__tuples__pb2.CreateTuplesRequest.SerializeToString,
            relations_dot_v0_dot_relation__tuples__pb2.CreateTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadTuples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kessel.relations.v0.KesselTupleService/ReadTuples',
            relations_dot_v0_dot_relation__tuples__pb2.ReadTuplesRequest.SerializeToString,
            relations_dot_v0_dot_relation__tuples__pb2.ReadTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTuples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kessel.relations.v0.KesselTupleService/DeleteTuples',
            relations_dot_v0_dot_relation__tuples__pb2.DeleteTuplesRequest.SerializeToString,
            relations_dot_v0_dot_relation__tuples__pb2.DeleteTuplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
